(* Any whitespace *)
ws_unit := space | tab | cr | lf ;
ws := ws_unit | {ws_unit} ;



file_content := { [ws], section }, [ws];
section := [ [ws], section_header ] , [ [ws], section_body];
section_header := "_s_" ;
section_body := [ list_of_body_units ] , [[ws], list_of_subsections];
variable_line :=  [ws], "_v_";
list_of_body_units := [ws], variable_line, { [ws], variable_line } ;
list_of_subsections := subsection, { [ws], subsection } ;
subsection := subsection_header, [ [ws], list_of_body_units ] ;
subsection_header := "_ss_";


ac := ? Terminals.AnyChar ? ;
eol := ? Terminals.Eol ? ;
space := " " ;
tab := "\x0009" ;
lf := "\x000A" ;
cr := "\x000D" ;
backslash := "\x005C" ;
dquote := '\x0022' ;
