(* Any whitespace *)
ws_unit := space | tab | cr | lf ;
ws := ws_unit, {ws_unit} ;

file_content := space_at_start_of_file, [section, { space_between_sections , section }], space_at_end_of_file ;
section := [ section_header ] , [ space_before_section_body, section_body ] ;
section_header := "_s_" ;
section_body := [ list_of_body_units ] , [ space_between_variables_and_subsections, list_of_subsections ] ;
variable_line := "_v_";
list_of_body_units := variable_line, { space_between_variable_lines, variable_line } ;
list_of_subsections := subsection, { space_between_subsections, subsection } ;
subsection := subsection_header, [ space_after_subsection_header, list_of_body_units ] ;
subsection_header := "_ss_";

space_at_start_of_file := [ws] ;
space_between_sections := [ws] ;
space_before_section_body := [ws] ;
space_between_variable_lines := [ws] ;
space_between_variables_and_subsections := [ws] ;
space_after_subsection_header := [ws] ;
space_between_subsections := [ws] ;
space_at_end_of_file := [ws] ;

ac := ? Terminals.AnyChar ? ;
eol := ? Terminals.Eol ? ;
space := " " ;
tab := "\x0009" ;
lf := "\x000A" ;
cr := "\x000D" ;
backslash := "\x005C" ;
dquote := "\x0022" ;
