letterenglishlarge = "A"|"B"|"C"|"D"|"E"|"F"|"G"|"H"|"I"|"J"|"K"|"L"|"M"|"N"|"O"|"P"|"Q"|"R"|"S"|"T"|"U"|"V"|"W"|"X"|"Y"|"Z" ;

letterenglishsmall = "a"|"b"|"c"|"d"|"e"|"f"|"g"|"h"|"i"|"j"|"k"|"l"|"m"|"n"|"o"|"p"|"q"|"r"|"s"|"t"|"u"|"v"|"w"|"x"|"y"|"z" ;

letterrussianlarge = "А"|"Б"|"В"|"Г"|"Д"|"Е"|"Ё"|"Ж"|"З"|"И"|"Й"|"К"|"Л"|"М"|"Н"|"О"|"П"|"Р"|"С"|"Т"|"У"|"Ф"|"Х"|"Ц"|"Ч"|"Ш"|"Щ"|"Ъ"|"Ы"|"Ь"|"Э"|"Ю"|"Я" ;

letterrussiansmall = "а"|"б"|"в"|"г"|"д"|"е"|"ё"|"ж"|"з"|"и"|"й"|"к"|"л"|"м"|"н"|"о"|"п"|"р"|"с"|"т"|"у"|"ф"|"х"|"ц"|"ч"|"ш"|"щ"|"ъ"|"ы"|"ь"|"э"|"ю"|"я" ;

letterenglish = letterenglishlarge | letterenglishsmall ;

letterrussian = letterrussianlarge | letterrussiansmall ;

letter = letterenglish | letterrussian;

digit = "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" ;

digitexcludingzero = digit - "0" ;

space = " " | "\t" ;

separator = "\n\r" | "\n" | "\r"  ;

spaces = space, {space} ;

minus =  "-" ;

dquote = '"' ;

backslash = "\\" ;

specialsequence = backslash, dquote | backslash, backslash | backslash, "n" | backslash, "t" | backslash, "b" ;

lbracket = "[";

rbracket = "]";

punctuationmarks = lbracket | rbracket | dquote | minus | "." | ";" | "#" ;

startofcomment = "#" | ";" ;

linecontinuation = backslash, lineseparator ;

raw_symbol_inside_quotes = ? Terminals.AnyChar ? - ( dquote | specialsequence | linecontinuation );

textofcomment = { digit | letter | punctuationmarks } ;

unitedlineseparator = {spaces} , { lineseparator, {spaces} } ;

symbol = allowedsymbol | nonallowedsymbol;

allowedsymbol = letterrussian | letterenglish | digit | punctuationmarks | spaces ;

comment = startofcomment , {textofcomment} ;

separator = spaces | unitedlineseparator | comment ;













variable = ( variablename, { {separator}, "=", {separator}, variablevalue } )
             |  ( "include.path",  {separator},  "=",  {separator},  filepath )
;


variablename = letterenglish, { letterenglish | [minus], letterenglish} ;

variablevalue = quotedstringwithcontinuations | unquotedstringinthewild ;

quotedstring = dquote, {allowedsymbol | spaces | specialsequence}, dquote ;

quotedstringwithcontinuations = dquote , { allowedsymbol | spaces | specialsequence | linecontinuation }, dquote ;

unquotedstringinthewildmeat = allowedsymbol | specialsequence ;

unquotedstringinthewild = unquotedstringinthewildmeat , { unquotedstringinthewildmeat } ,
    { { spaces | linecontinuation} , unquotedstringinthewildmeat } , [separator] ;


subsectiontitleunit = raw_symbol_inside_quotes | specialsequence ;

subsectiontitle = sectiontitleunit, {sectiontitleunit} ;

sectiontitleunit = letter | minus | "." ;

sectiontitle = sectiontitleunit, { sectiontitleunit } ;

subsectionbody = variable , { {separator} , variable } ;

subsection = subsectionheader, {separator}, subsectionbody ;

sectionbody = variable , { {separator} , variable } , { {separator} , subsection } ;

subsectionheader = lbracket , {spaces} , sectiontitle , spaces, {spaces} , dquote , subsectiontitle , dquote , {spaces} , rbracket ;

sectionheader = lbracket, {spaces}, sectiontitle, {spaces}, rbracket ;

section = ( sectionheader, {separator}, sectionbody ) 
	| ( subsection, { {separator}, subsection } ) 
	;

filecontent = [separator] , {section , {separator} } , [separator] ;

