<пробелы> ::= ( ' ' | '\t' ) + ;

<разделитель-строк> ::= '\n\r' | '\n' | '\r' ; 

<знаки-пунктуации> ::= '[' | ']' | '"' | '-' | '.' | ';' | '#' ;

<символ-комментария> ::= '#' | ';' ;

<хитрый-перенос> ::= '\' <разделитель-строк> ;

<буква-английская-большая> ::= [A-Z] ;

<буква-английская-маленькая> ::= [a-z] ;

<буква> ::= <буква-английская-большая> | <буква--английская-маленькая> ;

<специальная-последовательность> ::= '\"' | '\\' | '\n' | '\t' | '\b' ;

<обобщенный-разделитель-строк> ::= ( <пробелы> ? <разделитель-строк> <пробелы> ? ) + ;

<символ> ::= <допустимый-символ> | <недопустимый-символ>;

<допустимый-символ> ::= <буква-русская> | <буква-английская> | <цифра> | <знаки-пунктуации> | <пробелы> ;

<комментарий> ::= <символ-комментария> <текст-комментария> * ;

<текст-комментария> ::= . ;

<разделитель> ::= <пробелы> | <обобщенный-разделитель-строк> | <комментарий> ;

<текстовая-строка> ::= '"' ( <допустимый-символ> | <пробелы> | <специальная-последовательность> ) * '"' ;

<полезное-содержимое> ::= ( <секция разделитель> * ) * ;

<секция> ::= <заголовок-секции> <разделитель> * <тело-секции> ;

<тело-секции> ::= (<переменная разделитель> *) * | (<подсекция> <разделитель> *) * ;

<секция> ::= ( <подсекция> <разделитель> * ) * ;

<заголовок-секции> ::= '[' <пробелы> * <название-секции> <пробелы>* ']' ;

<название-секции> ::= ( <буква> | '-' | '.' ) + ;

<подсекция> ::= <заголовок-подсекции> <разделитель> * <тело-подсекции> ;

<заголовок-секции> ::= '[' <пробелы> * <название-секции> <пробелы> * '"' <заголовок-подсекции> '"' <пробелы> * ']' ;

<тело-подсекции> ::= ( <переменная> <разделитель> * ) * ;

<переменная> ::= <имя-переменной> ( <разделитель> * '=' <разделитель> * <значение-переменной> ) ?
             || 'include.path' <разделитель> * '=' <разделитель>* <путь-до-файла>
;

<заголовок-подсекции> ::= ( '\"' | '\\' | <допустимый-символ> | <пробелы> ) + ;

<имя-переменной> ::= <буква-английская> ( <буква-английская> | '-' ) * ;

<значение-переменной> ::= <строка-переносами-в-кавычках> | <строка-переносами-без-кавычек> ;

<строка-с-переносами-в-кавычках> ::= '"' ( <допустимый-символ> | <пробелы> | <специальная-последовательность> | <хитрый-перенос> ) * '"' ;

<строка-переносами-без-кавычек> ::= ( ( <допустимый-символ> | <специальная-последовательность> )*
     <пробелы> | <хитрый-перенос> ) * ( <допустимый-символ> | <специальная-последовательность> ) <разделитель> ? ;
