file_content = subsection , {  subsection } ;
subsection = section_start, { section_line } ;
section_start =  '[',  { ? Terminals.AnyChar ? - ']' },  ']' ;
section_line = { line_symbol };
line_symbol = ? Terminals.AnyChar ? - "[" ;
